

Test POST /spam/v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/internal/Spam/POST/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/internal/Spam/POST/v1/**/*

Staging POST /spam/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_STAGING --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6769386d00295a0defad
  environment: 
    name: staging/post_spam_v1
    url: $API_HOSTNAME/case/v1
  needs:
    - Test POST /spam/v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/internal/Spam/POST/v1/**/*

Production POST /spam/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_PROD --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 67693a730025fb437687
  environment: 
    name: production/post_spam_v1
    url: $API_HOSTNAME/case/v1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
      - functions/internal/Spam/POST/v1/**/*
      when: manual
        