
ports:
  - name: Parser Endpoint
    description: Translates HTTP to Functions
    port: 80
    onOpen: notify

  - name: Function server
    port: 3000
    visibility: public

tasks:
  - name: Install Parser and Appwrite
    init: cd parser/src && composer install && docker build . -t parser
    command: npm i -g appwrite-cli && appwrite client --endpoint https://appwrite.jrbit.de/v1 --projectId $APPWRITE_PROJECT --key $APPWRITE_API_KEY

  - name: Function Server
    init: cd function_server && npm install
    command: echo "Point with API_SCRIPT to your function"

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - TeamHub.teamhub
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - GitLab.gitlab-workflow
    - DEVSENSE.composer-php-vscode
    - caponetto.vscode-diff-viewer
    - 42Crunch.vscode-openapi
