
ports:
  - name: Parser Endpoint
    description: Translates HTTP to Functions
    port: 80
    onOpen: notify

tasks:
  - name: Install Dependencies
    init: ./.gitpod/init.sh
    command: ./dev-env.sh

    
  - name: PHP FPM
    command: sudo mkdir /run/php; sudo /usr/sbin/php-fpm8.1 -F -R


  - name: Nginx
    command: sudo nginx -c ${GITPOD_REPO_ROOT}/parser/nginx/local.conf

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - eamodio.gitlens
    - TeamHub.teamhub
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - GitLab.gitlab-workflow
    - DEVSENSE.composer-php-vscode
    - caponetto.vscode-diff-viewer
    - 42Crunch.vscode-openapi
