 
Test GET /docbotrecord/v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/public/DocbotRecords/GET/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/public/DocbotRecords/GET/v1/**/*
        
Staging GET /docbotrecord/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_STAGING --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6765def900168166ed36
  environment: 
    name: staging/get_docbotrecord_v1
    url: $API_HOSTNAME/docbotrecord/v1
  needs:
    - Test GET /docbotrecord/v1
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/DocbotRecords/GET/v1/**/*

        
Production GET /docbotrecord/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_PROD --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6767c9a7001c485bbec8
  environment: 
    name: production/get_docbotrecord_v1
    url: $API_HOSTNAME/docbotrecord/v1
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/DocbotRecords/GET/v1/**/*
        when: manual
