
Test GET /v1/service/all.json:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/public/Service/GET/LegacyV1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/public/Service/GET/LegacyV1/**/*

Staging GET /v1/service/all.json:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_STAGING --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6765d93e0024ddee13ef
  environment: 
    name: staging/get_v1_service_all_json
    url: $API_HOSTNAME/v1/service/all.json
  needs:
    - Test GET /v1/service/all.json
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/Service/GET/LegacyV1/**/*

Production GET /v1/service/all.json:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_PROD --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6767c7a30007aec8a80f
  environment: 
    name: production/get_v1_service_all_json
    url: $API_HOSTNAME/v1/service/all.json
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/Service/GET/LegacyV1/**/*
        when: manual