 
Test POST /docbotrecord/v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/public/DocbotRecords/POST/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/public/DocbotRecords/POST/v1/**/*
        
Staging POST /docbotrecord/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_STAGING --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6765df44000bba882da4
  environment: 
    name: staging/post_docbotrecord_v1
    url: $API_HOSTNAME/docbotrecord/v1
  needs:
    - Test POST /docbotrecord/v1
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/DocbotRecords/POST/v1/**/*

Production POST /docbotrecord/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_PROD --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6767c9ef0010311f673a
  environment: 
    name: production/post_docbotrecord_v1
    url: $API_HOSTNAME/docbotrecord/v1
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/DocbotRecords/POST/v1/**/*
        when: manual
