 
Test POST /point/v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/public/Point/POST/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/public/Point/POST/v1/**/*

Staging POST /point/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_STAGING --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6765de7f0037663ce53b
  environment: 
    name: staging/post_point_v1
    url: $API_HOSTNAME/point/v1
  needs:
    - Test POST /point/v1
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/Point/POST/v1/**/*

Production POST /point/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_PROD --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6767c9150006495b3db7
  environment: 
    name: production/post_point_v1
    url: $API_HOSTNAME/point/v1
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/Point/POST/v1/**/*
        when: manual
