openapi: 3.0.3
info:
  title: ToS;DR Service API
  description: Welcome to the ToS;DR Service API Documentation.
  termsOfService: https://tosdr.org/legal
  contact:
    email: team@tosdr.org
  license:
    name: CC BY-SA 3.0
    url: https://creativecommons.org/licenses/by-sa/3.0/
  version: 1.0.0
externalDocs:
  description: Find out more about ToS;DR
  url: https://tosdr.org
servers:
  - url: https://api.tosdr.org
  - url: https://api.staging.tosdr.org
tags:
  - name: Service
    description: Retrieve Infos about a specific service


paths:
  $ref#servicev1: '../functions/public/Service/GET/v1/spec/service.yaml'
  $ref#servicev2: '../functions/public/Service/GET/v2/spec/service.yaml'
  $ref#documentv1: '../functions/public/Document/GET/v1/spec/document.yaml'
  $ref#pointv1: '../functions/internal/Point/spec/point.yaml'
  $ref#docbotrecordv1: '../functions/internal/DocbotRecords/spec/docbotrecord.yaml'

components:
  schemas:
      $ref#all-services-v1: './components/service/all-services-v1.yaml'
      $ref#single-service-v1: './components/service/single-service-v1.yaml'
      $ref#all-services-v2: './components/service/all-services-v2.yaml'
      $ref#single-service-v2: './components/service/single-service-v2.yaml'
      $ref#document-v1: './components/document/document-v1.yaml'
      $ref#points-v1: './components/point/points-v1.yaml'
      $ref#single-point-v1: './components/point/single-point-v1.yaml'

  securitySchemes:
    api_key:
      type: apiKey
      name: apikey
      in: header


