version: '2.2'
services:

  parser:
    build: .
    ports:
      - 3000:80
    volumes:
      - ./docker/entrypoint.sh:/opt/entrypoint.d/entrypoint.sh
      - ./nginx/docker.conf:/etc/nginx/conf.d/default.conf
      - ./src:/app
    environment:
      - APPWRITE_HOSTNAME
      - APPWRITE_PROJECT
      - APPWRITE_API_KEY