 
Test GET /point/v1:
  stage: test_functions
  image: node:16
  script:
    - cd "functions/public/Point/GET/v1"
    - npm install
    - npm run build
  rules:
      - changes:
        - functions/public/Point/GET/v1/**/*
        
Staging GET /point/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_STAGING --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6765dd0f002a9c07a807
  environment: 
    name: staging/get_point_v1
    url: $API_HOSTNAME/point/v1
  needs:
    - Test GET /point/v1
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/Point/GET/v1/**/*

        
Production GET /point/v1:
  stage: deploy_functions
  image: node:16
  script:
    - npm i -g appwrite-cli && appwrite client --endpoint $APPWRITE_HOSTNAME --projectId $APPWRITE_PROJECT_PROD --key $APPWRITE_API_KEY
    - appwrite deploy function --functionId 6767c8b5001d8df32971
  environment: 
    name: production/get_point_v1
    url: $API_HOSTNAME/point/v1
  rules:
      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        changes:
        - functions/public/Point/GET/v1/**/*
        when: manual
